j2s7s300:
    type: effort_controllers/JointTrajectoryController
    joints:
        - j2s7s300_joint_1
        - j2s7s300_joint_2
        - j2s7s300_joint_3
        - j2s7s300_joint_4
        - j2s7s300_joint_5
        - j2s7s300_joint_6
        - j2s7s300_joint_7
    constraints:
      goal_time: 1.0
      stopped_velocity_tolerance: 0.02
      j2s7s300_joint_1:
        goal: 0.02
        trajectory: 0.05
      j2s7s300_joint_2:
        goal: 0.02
        trajectory: 0.05
      j2s7s300_joint_3:
        goal: 0.02
        trajectory: 0.05
      j2s7s300_joint_4:
        goal: 0.02
        trajectory: 0.05
      j2s7s300_joint_5:
        goal: 0.02
        trajectory: 0.05
      j2s7s300_joint_6:
        goal: 0.02
        trajectory: 0.05
      j2s7s300_joint_7:
        goal: 0.02
        trajectory: 0.05
    gains:
      j2s7s300_joint_1:
        d: 0
        i: 0
        i_clamp: 10
        p: 2000
      j2s7s300_joint_2:
        d: 0
        i: 0
        i_clamp: 10
        p: 3000
      j2s7s300_joint_3:
        d: 0
        i: 0
        i_clamp: 10
        p: 1000
      j2s7s300_joint_4:
        d: 0
        i: 0
        i_clamp: 10
        p: 2000
      j2s7s300_joint_5:
        d: 0
        i: 0
        i_clamp: 10
        p: 200
      j2s7s300_joint_6:
        d: 0
        i: 0
        i_clamp: 10
        p: 500
      j2s7s300_joint_7:
        d: 0
        i: 0
        i_clamp: 10
        p: 200

    stop_trajectory_duration: 0.5
    state_publish_rate:  100
    action_monitor_rate: 10
